# Alpine slurm config file for lib2_6frogs

executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p results/lib2_6frogs/slurm_logs/{rule} &&
  sbatch
    --partition=amilan
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --qos={resources.qos}
    --job-name=smk-{rule}-{wildcards}
    --output=results/lib2_6frogs/slurm_logs/{rule}/{rule}-%j-{wildcards}.out
    --error=results/lib2_6frogs/slurm_logs/{rule}/{rule}-%j-{wildcards}.err
    --parsable
cluster-generic-status-cmd: status-sacct-robust.sh
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 4000
default-resources:
  - time="08:00:00"
  - mem_mb=3740
  - qos="normal"
  - tmpdir="results/lib2_6frogs/snake-tmp"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 50
local-cores: 1
latency-wait: 60
cores: 2400
jobs: 450
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
keep-incomplete: True
rerun-trigger: mtime
